credentials:
  usernames:
    demo:
      name: "Demo User"
      password: "$2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW"
    test:
      name: "Test User"  
      password: "$2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW"

cookie:
  name: "mind_balance_cookie"
  key: "random_signature_key_123"
  expiry_days: 30